#!/bin/bash
# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


set -o errexit

readonly BUF_IMG=bufbuild/buf:1.58.0

declare SERVICE_NAME=
declare RPC=
declare REQUEST_TYPE=
declare DATA_FILE=
declare PROTO_FILE=

function usage() {
  local -i exitval=${1-1}
  cat <<EOF
Usage: $0 OPTION...

Options:
  --service-name   The gRPC service name.
  --rpc            The gRPC method name.
  --request-type   The fully qualified protobuf request message type.
  --data-file      The path to the input data file (JSON).
  --proto-file     The path to the .proto file defining the request type.
  -h, --help       Display this help message.
EOF
  exit ${exitval}
}

# Parse command-line arguments
while [[ $# -gt 0 ]]; do
  key="$1"
  case $key in
    --service-name)
      SERVICE_NAME="$2"
      shift 2 || usage
      ;;
    --rpc)
      RPC="$2"
      shift 2 || usage
      ;;
    --request-type)
      REQUEST_TYPE="$2"
      shift 2 || usage
      ;;
    --data-file)
      DATA_FILE="$2"
      shift 2 || usage
      ;;
    --proto-file)
      PROTO_FILE="$2"
      shift 2 || usage
      ;;
    -h|--help) usage 0 ;;
    *)
      printf "Unknown option: %s\n" "$1"
      usage
      ;;
  esac
done

if [[ -z ${SERVICE_NAME} ]] || [[ -z ${RPC} ]] || [[ -z ${REQUEST_TYPE} ]] || [[ -z ${DATA_FILE} ]] || [[ -z ${PROTO_FILE} ]]; then
  printf "Error: Missing required arguments." >&2
  usage
fi

function buf() {
  docker run --rm -i --volume="${PWD}":/work --workdir=/work "${BUF_IMG}" "$@"
}

ENCODED_REQ="$(buf convert "${PROTO_FILE}" --from="${DATA_FILE}" --type="${REQUEST_TYPE}" --to=-#format=binpb | base64 --wrap=0)"

cat <<EOF
{
  "control_plane_metadata": {
    "destination_service_name": "${SERVICE_NAME}",
    "destination_method_name": "${RPC}"
  },
  "isolate_input": {
    "datagrams": ["${ENCODED_REQ}"]
  }
}
EOF
